import { Grid, GridItem } from '@chakra-ui/react'
import Head from 'next/head'

import { UserRegisterForm } from '@/presentation/components'

export default function PatientRegister() {
  return (
    <>
      <Head>
        <title>MedMais - Marcar consultas com médicos, dentistas ou exames de laboratório</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Grid
        gridTemplateColumns={'1fr 1fr'}
        height={'100vh'}
      >
        <GridItem>
          <UserRegisterForm />
        </GridItem>
        <GridItem
          backgroundColor={'teal.600'}
        >

        </GridItem>
      </Grid>
    </>
  )
}