import {
  Box,
  Button,
  Flex,
  FormControl,
  Heading,
  HStack, IconButton, Input,
  Spinner,
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  Tooltip,
  Tr,
  useDisclosure,
  useToast
} from '@chakra-ui/react'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { parseCookies } from 'nookies'
import { useState } from 'react'
import { AiOutlineEdit } from 'react-icons/ai'
import { BiTrashAlt } from 'react-icons/bi'
import { RxUpdate } from 'react-icons/rx'
import { useQuery } from 'react-query'

import { fetchExamSearch, realFormatter } from '@/application/helpers'
import { ExamResponse } from '@/domain/models'
import { api } from '@/infra/config'
import { CreateExamModal, DashboardLayout } from '@/presentation/components'

export default function DashboardExams() {
  const toast = useToast()
  const [searchTerm, setSearchTerm] = useState('')
  const [foundExams, setFoundExams] = useState<ExamResponse[]>()
  const createExameModal = useDisclosure()

  const handleExamSearch = async () => {
    if (searchTerm === '') {
      toast({
        status: 'warning',
        description: 'Você precisa inserir uma informação na busca!',
        duration: 1000
      })
    } else {
      const examsFound = await fetchExamSearch(searchTerm)
      setFoundExams(examsFound)
    }
  }

  const fetchExams = async () => {
    const { data } = await api.get<ExamResponse[]>('/api/exam/all')
    return data
  }

  const { data: exams, isLoading, isError, refetch, isRefetching } = useQuery('exams', fetchExams, {
    staleTime: 1000 * 60 * 60
  })

  const handleRefectch = async () => {
    await refetch({ queryKey: 'exams' })
  }

  return (
    <>
      <Head>
        <title>MedMais - Painel de administração clínica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <DashboardLayout>
        <Flex alignItems={'center'} width={'100%'} justifyContent={'space-between'}>
          <Heading as='h1' fontSize={'xl'} color={'gray.600'}>
            Exames
          </Heading>
          <Button
            variant={'outline'}
            colorScheme={'teal'}
            onClick={createExameModal.onOpen}
          >
            Adicionar exame
          </Button>
        </Flex>
        <Flex as='form' margin={'16px 0'} gap={'8px'} maxWidth={{ lg: '70%' }}>
          <FormControl>
            <Input type='text' onChange={(e) => setSearchTerm(e.target.value)} />
          </FormControl>
          <Button
            color={'white'}
            backgroundColor={'teal.400'}
            _hover={{
              backgroundColor: 'teal.500'
            }}
            onClick={handleExamSearch}
            boxShadow={{ lg: 'lg' }}
          >
            Procurar
          </Button>
        </Flex>
        <Flex
          alignItems={'center'}
          width={'100%'}
          justifyContent={'flex-end'}
          paddingY={2}
          gap={2}
        >
          <Button
            variant={'outline'}
            colorScheme={'teal'}
            onClick={() => setFoundExams(undefined)}
            leftIcon={<RxUpdate />}
            size={'xs'}
          >
            Limpar busca
          </Button>
          <Button
            colorScheme={'teal'}
            onClick={handleRefectch}
            leftIcon={<RxUpdate />}
            size={'xs'}
            isLoading={isRefetching}
          >
            Atualizar
          </Button>
        </Flex>
        <Box
          border={'1px'}
          borderColor={'gray.200'}
          borderRadius={{ lg: 'xl' }}
        >
          {
            isLoading ? (
              <Box padding={4}>
                <Spinner />
              </Box>
            ) : isError ? (
              <Box padding={4}>
                <Heading as='h2' fontSize={'lg'}>
                  Ocorreu um erro ao encontrar os exames
                </Heading>
              </Box>
            ) : (exams?.length === 0) ? (
              <Box padding={4}>
                <Heading as='h2' fontSize={'lg'} color={'gray.600'}>
                  Você ainda não possui exames cadastrados
                </Heading>
              </Box>
            ) : (
              <Table>
                <Thead>
                  <Tr>
                    <Th>Exame</Th>
                    <Th>Preço</Th>
                    <Th></Th>
                  </Tr>
                </Thead>
                <Tbody>
                  {
                    (foundExams !== undefined) ? (
                      foundExams?.map((exam, index) => {
                        return (
                          <Tr key={index}>
                            <Td width={'65%'}>{exam.name}</Td>
                            <Td>{realFormatter.format(Number(exam.price))}</Td>
                            <Td>
                              <HStack
                                justifyContent={'flex-end'}
                              >
                                <Tooltip label={'Editar paciente'} borderRadius={'md'}>
                                  <IconButton
                                    aria-label='edit-patient'
                                    size={{ lg: 'sm' }}
                                  >
                                    <AiOutlineEdit />
                                  </IconButton>
                                </Tooltip>
                                <Tooltip label={'Excluir paciente'} borderRadius={'md'} bg={'red'}>
                                  <IconButton
                                    aria-label='edit-patient'
                                    size={{ lg: 'sm' }}
                                  >
                                    <BiTrashAlt />
                                  </IconButton>
                                </Tooltip>
                              </HStack>
                            </Td>
                          </Tr>
                        )
                      })
                    ) : (
                      exams?.map((exam, index) => {
                        return (
                          <Tr key={index}>
                            <Td width={'65%'}>{exam.name}</Td>
                            <Td>{realFormatter.format(Number(exam.price))}</Td>
                            <Td>
                              <HStack
                                justifyContent={'flex-end'}
                              >
                                <Tooltip label={'Editar exame'} borderRadius={'md'}>
                                  <IconButton
                                    aria-label='edit-patient'
                                    size={{ lg: 'sm' }}
                                  >
                                    <AiOutlineEdit />
                                  </IconButton>
                                </Tooltip>
                                <Tooltip label={'Excluir exame'} borderRadius={'md'} bg={'red'}>
                                  <IconButton
                                    aria-label='edit-patient'
                                    size={{ lg: 'sm' }}
                                  >
                                    <BiTrashAlt />
                                  </IconButton>
                                </Tooltip>
                              </HStack>
                            </Td>
                          </Tr>
                        )
                      })
                    )
                  }
                </Tbody>
              </Table>
            )
          }
        </Box>
      </DashboardLayout>
      <CreateExamModal isOpen={createExameModal.isOpen} onClose={createExameModal.onClose} />
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const cookies = parseCookies(ctx)

  if (cookies['medmais.access_token'] === undefined) {
    return {
      redirect: {
        destination: '/login-necessario',
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}