import { Text } from '@chakra-ui/react'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { parseCookies } from 'nookies'

import { DashboardLayout } from '@/presentation/components'

export default function Dashboard () {
  return (
    <>
      <Head>
        <title>MedMais - Painel de administração clínica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <DashboardLayout>
        <Text>Content</Text>
      </DashboardLayout>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const cookies = parseCookies(ctx)

  if (cookies['medmais.access_token'] === undefined) {
    return {
      redirect: {
        destination: '/login-necessario',
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}