import { Text } from '@chakra-ui/react'

import { DashboardLayout } from '@/presentation/components'
import Head from 'next/head'

export default function Dashboard () {
  return (
    <>
      <Head>
        <title>MedMais - Painel de administração clínica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <DashboardLayout>
        <Text>Content</Text>
      </DashboardLayout>
    </>
  )
}