import { Box } from '@chakra-ui/react'
import { Inter } from 'next/font/google'
import Head from 'next/head'

import { LoginForm } from '../components'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MedMais - Painel de administração clínica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Box as='main'>
        <LoginForm />
      </Box>
    </>
  )
}
