import { Box } from '@chakra-ui/react'
import { Inter } from 'next/font/google'
import Head from 'next/head'

import { ValidateTokenService } from '@/application/services'
import { DayjsService } from '@/infra/libs'
import { LoginForm } from '@/presentation/components'
import { GetServerSideProps } from 'next'
import { parseCookies } from 'nookies'

const inter = Inter({ subsets: ['latin'] })

export default function Login() {
  return (
    <>
      <Head>
        <title>MedMais - Painel de administração clínica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Box as='main'>
        <LoginForm />
      </Box>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const cookies = parseCookies(ctx)

  if (cookies['medmais.access_token'] !== undefined) {
    const dayjsService = new DayjsService()
    const validateTokenSerive = new ValidateTokenService(cookies['medmais.access_token'], dayjsService)
    validateTokenSerive.execute()

    return {
      props: {}
    }
  }

  return {
    props: {}
  }
}